<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Qcentris-396" failures="1" tests="5" name="Default test" time="90.288" errors="0" timestamp="2025-02-15T15:42:03 EET">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="10.371">
    <failure type="java.lang.AssertionError" message="Expected error message: Epic sadface: Epic sadface: Password is required but got: Epic sadface: Username and password do not match any user in this service expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Expected error message: Epic sadface: Epic sadface: Password is required but got: Epic sadface: Username and password do not match any user in this service expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at tests.ErrorValidationTestStepDefinitions.iShouldSeeAnErrorMessage(ErrorValidationTestStepDefinitions.java:36)
at âœ½.I should see an error message "Epic sadface: Epic sadface: Password is required"(file:///C:/Users/Mahmoud.Gomaa/eclipse-workspace/Demo/src/main/resources/ErrorValidation.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="9.519"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.956"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.939"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="54.775"/>
</testsuite> <!-- Default test -->
