<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Qcentris-396" failures="1" tests="2" name="LoginErrorValidation" time="10.778" errors="0" timestamp="2025-01-19T14:01:38 EET">
  <testcase classname="tests.ErrorValidationTest" name="testInvalidLoginLandingPage" time="2.345">
    <skipped/>
  </testcase> <!-- testInvalidLoginLandingPage -->
  <testcase classname="tests.ErrorValidationTest" name="testInvalidLoginLandingPage" time="1.429">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at tests.ErrorValidationTest.testInvalidLoginLandingPage(ErrorValidationTest.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testInvalidLoginLandingPage -->
</testsuite> <!-- LoginErrorValidation -->
